# Shared history defaults.
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=$HOME/.zsh_history

setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS