#!/usr/bin/env python3
"""Generate committed code-point width intervals from Python's Unicode data.

This is a maintenance command, never a shell-startup dependency. Terminal
ambiguous width and emoji grapheme shaping remain terminal-dependent.
"""
from pathlib import Path
import unicodedata


def intervals(predicate):
    start = previous = None
    result = []
    for code in range(0x110000):
        if predicate(code):
            if start is None:
                start = code
            previous = code
        elif start is not None:
            result.append((start, previous))
            start = previous = None
    if start is not None:
        result.append((start, previous))
    return result


zero = intervals(lambda code: unicodedata.category(chr(code)) in {"Mn", "Me", "Cf"}
                 or 0x1160 <= code <= 0x11FF)
wide = intervals(lambda code: unicodedata.category(chr(code)) != "Cn"
                 and unicodedata.east_asian_width(chr(code)) in {"W", "F"})
lines = [f"# Generated by scripts/generate-width-data.py; Unicode {unicodedata.unidata_version}.",
         "# Fixed data only. Loaded on first non-ASCII width measurement."]
for name, ranges in (("ZERO", zero), ("WIDE", wide)):
    for position, label in ((0, "START"), (1, "END")):
        lines.append(f"typeset -ga _ZSH_UI_{name}_{label}=(")
        values = [f"0x{pair[position]:X}" for pair in ranges]
        for index in range(0, len(values), 12):
            lines.append("  " + " ".join(values[index:index + 12]))
        lines.append(")")
lines.append("typeset -gi _ZSH_UI_WIDTH_DATA_LOADED=1")
(Path(__file__).resolve().parents[1] / "lib/ui-width-data.zsh").write_text("\n".join(lines) + "\n")
